const cartActionType = {
    TOGGLE_CART_ITEM : 'TOGGLE_CART_ITEM',
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART : 'CLEAR_ITEM_FROM_CART',
    REMOVE_FROM_CART : 'REMOVE_FROM_CART',
    ADD_FROM_CART : 'ADD_FROM_CART',
    CLEAR_CART : 'CLEAR_CART' 
}

export default cartActionType