<<<<<<< HEAD
const userActionTypes = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    GOOGLE_SIGNIN_START : 'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START : 'EMAIL_SIGNIN_START',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE : 'SIGN_IN_FAILURE',
    SIGN_OUT_START : 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS : 'SIGN_OUT_SUCCESS',
    SIGN_UP_START : 'SIGN_UP_START',
    SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE : 'SIGN_UP_FAILURE',
    SIGN_OUT_FAILURE : 'SIGN_OUT_FAILURE',
    CHECK_USER_SESSION : 'CHECK_USER_SESSION'
}


export default userActionTypes
=======
export const userActionTypes = {
    SET_CURRENT_USER : 'SET_CURRENT_USER'
}
>>>>>>> 9b05af884294eed7eecd753d150631b0fa065e4c
